# Generated by Django 4.0.5 on 2022-07-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choices_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choices',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
