# Generated by Django 4.0.5 on 2022-07-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choices_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
